[providers]
php = "8.2"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[phases.build]
cmds = ["php artisan storage:link", "php artisan migrate --force"]

[start]
cmd = "php -S 0.0.0:$PORT -t public"